### ISSUE TITLE
Bug in personalised pagerank?

### ISSUE THREAD

**Issue by MingfeiLiu3** [staglibrary/stagpy#44]
There is a possible bug in the personalised pagerank method when run with the parameters in the attached pickle file.

**Comment by pmacg** [comment]
After extracting the `arguments.pickle` file from the attached `arguments.zip` file, the following python script will reproduce the error.

```python
import stag.graph
import stag.random
import stag.cluster
import stag.graph
import pickle


def main():
    with open("arguments.pickle", 'rb') as fin:
        args = pickle.load(fin)
    g = stag.graph.Graph(args[0])
    vec = args[1].tocsc()
    alpha = args[2]
    eps = args[3]
    result = stag.cluster.approximate_pagerank(g, vec, alpha, eps)
    print(result)


if __name__ == "__main__":
    main()

```

**Comment by pmacg** [comment]
In actual fact, this is a bug only in the python library - we need to handle the empty sparse matrix correctly.
